const state={movies:[],featured:null,selected:null,query:"",filter:null,myList:new Set(JSON.parse(localStorage.getItem("myflix-list")||"[]")),progress:JSON.parse(localStorage.getItem("myflix-progress")||"{}")};
const $=s=>document.querySelector(s);const content=$("#content"),video=$("#videoPlayer");
async function loadLibrary(){try{const r=await fetch("library.json",{cache:"no-store"});if(!r.ok)throw new Error();const data=await r.json();state.movies=data.movies||[];state.featured=state.movies.find(m=>m.id===data.featuredId)||state.movies[0];renderHero();render();}catch{content.innerHTML=`<div class="empty-state"><h2>MyFlix needs to run from your website</h2><p>Upload all these files to GitHub Pages together. Opening index.html directly can stop the browser reading library.json.</p></div>`}}
function safeImage(url){return typeof url==="string"&&/^https?:\/\/|^[./]?[^:]+\.(jpg|jpeg|png|webp)$/i.test(url)?url:""}
function renderHero(){const m=state.featured;if(!m)return;$("#heroTitle").innerHTML=m.title.replace(/\s+/g," ");$("#heroDescription").textContent=m.description;$("#heroMeta").innerHTML=[m.year,m.runtime,m.genre,m.rating].filter(Boolean).map(x=>`<span>${x}</span>`).join("");const bg=safeImage(m.backdrop);$(".hero-backdrop").style.backgroundImage=bg?`url("${bg.replace(/"/g,"")}")`:""}
function filteredMovies(){return state.movies.filter(m=>{const q=state.query.toLowerCase();const matches=!q||[m.title,m.genre,m.year,m.type].join(" ").toLowerCase().includes(q);const type=!state.filter||m.type===state.filter;return matches&&type})}
function card(m){const node=$("#cardTemplate").content.firstElementChild.cloneNode(true),img=node.querySelector("img"),src=safeImage(m.poster);if(src){img.src=src;img.alt=`${m.title} poster`}else img.remove();node.querySelector("h3").textContent=m.title;node.querySelector(".card-meta").textContent=[m.year,m.genre].filter(Boolean).join(" • ");node.querySelector(".card-badge").textContent=m.type||"MOVIE";const p=state.progress[m.id];if(p>0){const track=node.querySelector(".progress-track");track.classList.remove("hidden");track.querySelector("span").style.width=`${Math.min(100,p)}%`}node.addEventListener("click",()=>openDetails(m));node.addEventListener("keydown",e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();openDetails(m)}});return node}
function makeRow(title,movies){if(!movies.length)return;const row=document.createElement("section");row.className="row";row.innerHTML=`<div class="row-header"><h2>${title}</h2><span class="row-count">${movies.length} title${movies.length===1?"":"s"}</span></div><div class="card-rail"></div>`;movies.forEach(m=>row.querySelector(".card-rail").append(card(m)));content.append(row)}
function render(){content.innerHTML="";let movies=filteredMovies();if(state.filter==="my-list")movies=movies.filter(m=>state.myList.has(m.id));if(!movies.length){content.innerHTML=`<div class="empty-state"><h2>Nothing here yet</h2><p>${state.filter==="my-list"?"Open a movie and press + to save it.":"Try another search."}</p></div>`;return}const watching=movies.filter(m=>state.progress[m.id]>0&&state.progress[m.id]<95);makeRow(state.query?`Results for “${state.query}”`:state.filter?state.filter:"Continue Watching",state.query||state.filter?movies:watching);if(!state.query&&!state.filter){const cats=[...new Set(movies.map(m=>m.category||m.genre).filter(Boolean))];cats.forEach(c=>makeRow(c,movies.filter(m=>(m.category||m.genre)===c)));makeRow("All Movies & Shows",movies)}}
function openDetails(m){state.selected=m;$("#detailTitle").textContent=m.title;$("#detailDescription").textContent=m.description;$("#detailMeta").innerHTML=[m.year,m.runtime,m.genre,m.rating].filter(Boolean).map(x=>`<span>${x}</span>`).join("");const bg=safeImage(m.backdrop||m.poster);$("#detailBackdrop").style.backgroundImage=bg?`url("${bg.replace(/"/g,"")}")`:"";updateListButton();$("#detailsModal").classList.remove("hidden")}
function updateListButton(){const added=state.selected&&state.myList.has(state.selected.id);$("#listButton").textContent=added?"✓":"＋";$("#listButton").setAttribute("aria-label",added?"Remove from My List":"Add to My List")}
function play(m){if(!m?.video)return;$("#detailsModal").classList.add("hidden");$("#playerError").classList.add("hidden");video.src=m.video;video.dataset.id=m.id;$("#playerModal").classList.remove("hidden");video.play().catch(()=>{})}
$("#heroPlay").onclick=()=>play(state.featured);$("#heroInfo").onclick=()=>openDetails(state.featured);$("#detailPlay").onclick=()=>play(state.selected);$("#listButton").onclick=()=>{const id=state.selected.id;state.myList.has(id)?state.myList.delete(id):state.myList.add(id);localStorage.setItem("myflix-list",JSON.stringify([...state.myList]));updateListButton();if(state.filter==="my-list")render()};
document.querySelectorAll("[data-close]").forEach(b=>b.onclick=()=>{const el=document.getElementById(b.dataset.close);el.classList.add("hidden");if(el.id==="playerModal"){video.pause();video.removeAttribute("src");video.load()}});
document.addEventListener("keydown",e=>{if(e.key==="Escape"){document.querySelectorAll(".modal:not(.hidden),.player-modal:not(.hidden)").forEach(x=>x.classList.add("hidden"));video.pause()}});
document.querySelectorAll("[data-filter]").forEach(b=>b.onclick=()=>{state.filter=b.dataset.filter;state.query="";setNav(b);render();window.scrollTo({top:500,behavior:"smooth"})});document.querySelectorAll("[data-view]").forEach(b=>b.onclick=()=>{state.filter=b.dataset.view==="library"?"my-list":null;state.query="";setNav(b);render();window.scrollTo({top:0,behavior:"smooth"})});function setNav(active){document.querySelectorAll(".nav-link").forEach(x=>x.classList.toggle("active",x===active))}
$("#searchButton").onclick=()=>{$("#searchPanel").classList.toggle("hidden");if(!$("#searchPanel").classList.contains("hidden"))$("#searchInput").focus()};$("#searchInput").oninput=e=>{state.query=e.target.value.trim();state.filter=null;render()};
video.addEventListener("timeupdate",()=>{if(!video.duration||!video.dataset.id)return;state.progress[video.dataset.id]=Math.round(video.currentTime/video.duration*100);localStorage.setItem("myflix-progress",JSON.stringify(state.progress))});video.addEventListener("error",()=>{const p=$("#playerError");p.textContent="This video file could not be loaded. Check its name and location in library.json.";p.classList.remove("hidden")});window.addEventListener("scroll",()=>$(".topbar").classList.toggle("scrolled",scrollY>30));loadLibrary();
